### ISSUE TITLE
[ISSUE] Activity Diary :: Missing Activities

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#10] opened 2018-11-18 22:19 UTC
Issue migrated to public repo.

Any activities that have a 12:00AM timestamp are not displayed in the application, if these timestamps are changed to 1:00AM, they display as expected.

**Comment by davcpas1234** [comment] 2019-02-13 16:37
This issue is being caused by an erroneous seconds issue.

In order to resolve this, the query needs to look at 23:59:59 of the previous day, despite using `.greaterThanOrEqualTo()` (<=) operator.

**Comment by davcpas1234** [comment] 2019-02-13 16:38
Fix implemented and this will be released in `v0.0.7`

**Closed as completed by davcpas1234** 2019-02-13 16:38 UTC
Labels: Type: bug, Status: released, Lang: java
