### ISSUE TITLE
v0.0.11 rc3 - thought not adding

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#98] opened 2019-11-29 11:42 UTC
**Application Version**
v0.0.11-rc3

**Issue Description**
Trying to add unreflected thought 

**Steps to Reproduce**
1. go to thought diary
2. add situation and 3 unhelpful thoughts (or less)
3. add 2 emotions
4. screen goes temporarily blank and returns to home menu - thought not added 

**Expected Behaviour**
thought should be added

**Screenshots (Optional)**

**Comment by davcpas1234** [comment] 2019-11-29 16:49
Caused by `AddRatingsActivity.java` line 208

Stack trace:
`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.set(int, java.lang.Object)' on a null object reference at uk.ac.bournemouth.facets.Activities.ThoughtDiary.AddRatingsActivity$1.onSeekBarValueChanged(AddRatingsActivity.java:208)
`

**Comment by davcpas1234** [comment] 2019-12-02 19:47
Resolved in `0.0.11-rc4`

**Closed as completed by davcpas1234** 2019-12-02 19:47 UTC
Labels: Type: bug, Status: released, Priority: high, Platform: android
